name: Python Tests

on: 
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Run tests
      run: |
        coverage run -m unittest discover  
        coverage report  
